Section "ServerLayout"
    Identifier "Rodnik"
    Screen 0 "Screen0"
    InputDevice "Keyboard0" "CoreKeyboard"
EndSection

Section "InputDevice"
    Identifier "Keyboard0"
    Driver "kbd"
    Option "XkbLayout" "us,ru"
    Option "XkbOptions" "grp:alt_shift_toggle"
EndSection

Section "Device"
    Identifier "GPU"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "GPU"
EndSection
