#!/bin/bash
# Генерация конфигов ядра ОС Родник (ядро 6.8)
set -e

KERNEL="/mnt/c/Projects/linux"
CONFIGS="$KERNEL/rodnik/configs"

mkdir -p "$CONFIGS"
cd "$KERNEL"

echo "=== Базовый конфиг ==="

make allnoconfig
cat >> .config << 'BASE'
CONFIG_64BIT=y
CONFIG_X86_64=y
CONFIG_SMP=y
CONFIG_MODULES=n
CONFIG_PCI=y
CONFIG_PCI_MSI=y
CONFIG_ACPI=y
CONFIG_ACPI_BUTTON=y
CONFIG_ACPI_FAN=y
CONFIG_ACPI_THERMAL=y
CONFIG_MICROCODE=y
CONFIG_MICROCODE_INTEL=y
CONFIG_CPU_FREQ=y
CONFIG_X86_INTEL_PSTATE=y
CONFIG_INTEL_IDLE=y
CONFIG_HZ=250
CONFIG_HIGH_RES_TIMERS=y
CONFIG_TTY=y
CONFIG_VT=y
CONFIG_VT_CONSOLE=y
CONFIG_UNIX98_PTYS=y
CONFIG_PRINTK=y
CONFIG_EARLY_PRINTK=y
CONFIG_INPUT=y
CONFIG_INPUT_MOUSEDEV=y
CONFIG_INPUT_EVDEV=y
CONFIG_INPUT_KEYBOARD=y
CONFIG_KEYBOARD_ATKBD=y
CONFIG_INPUT_MOUSE=y
CONFIG_MOUSE_PS2=y
CONFIG_HID=y
CONFIG_HID_GENERIC=y
CONFIG_USB_HID=y
CONFIG_USB_SUPPORT=y
CONFIG_USB=y
CONFIG_USB_XHCI_HCD=y
CONFIG_USB_XHCI_PCI=y
CONFIG_USB_STORAGE=y
CONFIG_EXT4_FS=y
CONFIG_EXT4_USE_FOR_EXT2=y
CONFIG_FAT_FS=y
CONFIG_VFAT_FS=y
CONFIG_NTFS_FS=y
CONFIG_NTFS3_FS=y
CONFIG_TMPFS=y
CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y
CONFIG_PROC_FS=y
CONFIG_SYSFS=y
CONFIG_BINFMT_ELF=y
CONFIG_BINFMT_SCRIPT=y
CONFIG_NLS=y
CONFIG_NLS_DEFAULT="utf8"
CONFIG_NLS_CODEPAGE_437=y
CONFIG_NLS_CODEPAGE_866=y
CONFIG_NLS_ISO8859_1=y
CONFIG_NLS_UTF8=y
CONFIG_NET=y
CONFIG_INET=y
CONFIG_IPV6=y
CONFIG_NETDEVICES=y
CONFIG_ETHERNET=y
CONFIG_NET_VENDOR_INTEL=y
CONFIG_E1000=y
CONFIG_E1000E=y
CONFIG_BT=y
CONFIG_BT_INTEL=y
CONFIG_BT_HCIUART=y
CONFIG_BT_HCIUART_INTEL=y
CONFIG_BT_HCIVHCI=y
CONFIG_BT_HCIBTUSB=y
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
CONFIG_DEBUG_INFO=n
CONFIG_DEBUG_KERNEL=n
CONFIG_KALLSYMS=n
CONFIG_MAGIC_SYSRQ=n
CONFIG_WIRELESS=n
CONFIG_WLAN=n
BASE

make olddefconfig
cp .config /tmp/rodnik-base.config
echo "OK"

# === ASUS NUC 14 Pro ===
echo "=== ASUS NUC 14 Pro ==="
cp /tmp/rodnik-base.config .config
cat >> .config << 'NUC'
CONFIG_WIRELESS=y
CONFIG_WLAN=y
CONFIG_WLAN_VENDOR_INTEL=y
CONFIG_IWLWIFI=y
CONFIG_IWLMVM=y
CONFIG_DRM=y
CONFIG_DRM_FBDEV_EMULATION=y
CONFIG_DRM_I915=y
CONFIG_DRM_XE=y
CONFIG_FB=y
CONFIG_FB_VESA=y
CONFIG_FB_EFI=y
CONFIG_FB_SIMPLE=y
CONFIG_FRAMEBUFFER_CONSOLE=y
CONFIG_SOUND=y
CONFIG_SND=y
CONFIG_SND_HDA_INTEL=y
CONFIG_SND_HDA_CODEC_HDMI=y
CONFIG_SND_HDA_CODEC_GENERIC=y
CONFIG_SND_HDA_CODEC_REALTEK=y
CONFIG_SND_HDA_GENERIC=y
CONFIG_INTEL_MEI=y
CONFIG_INTEL_MEI_ME=y
CONFIG_INTEL_MEI_HDCP=y
CONFIG_INTEL_MEI_PXP=y
CONFIG_INTEL_MEI_GSC=y
CONFIG_USB4=y
NUC
make olddefconfig
cp .config "$CONFIGS/rodnik-asus-nuc14.config"

# === Huawei MateBook D16 ===
echo "=== MateBook D16 ==="
cp /tmp/rodnik-base.config .config
cat >> .config << 'MATE'
CONFIG_WIRELESS=y
CONFIG_WLAN=y
CONFIG_WLAN_VENDOR_INTEL=y
CONFIG_IWLWIFI=y
CONFIG_IWLMVM=y
CONFIG_MOUSE_PS2_ELANTECH=y
CONFIG_MOUSE_PS2_SYNAPTICS=y
CONFIG_ACPI_BATTERY=y
CONFIG_POWER_SUPPLY=y
CONFIG_DRM=y
CONFIG_DRM_FBDEV_EMULATION=y
CONFIG_DRM_I915=y
CONFIG_FB=y
CONFIG_FB_VESA=y
CONFIG_FB_EFI=y
CONFIG_FB_SIMPLE=y
CONFIG_FRAMEBUFFER_CONSOLE=y
CONFIG_SOUND=y
CONFIG_SND=y
CONFIG_SND_HDA_INTEL=y
CONFIG_SND_HDA_CODEC_HDMI=y
CONFIG_SND_HDA_CODEC_GENERIC=y
CONFIG_SND_HDA_CODEC_REALTEK=y
CONFIG_SND_HDA_GENERIC=y
CONFIG_BACKLIGHT_LCD_SUPPORT=y
CONFIG_BACKLIGHT_CLASS_DEVICE=y
MATE
make olddefconfig
cp .config "$CONFIGS/rodnik-matebook-d16.config"

# === ASUS Vivobook Slate 13 ===
echo "=== Vivobook Slate 13 ==="
cp /tmp/rodnik-base.config .config
cat >> .config << 'VIVO'
CONFIG_WIRELESS=y
CONFIG_WLAN=y
CONFIG_WLAN_VENDOR_INTEL=y
CONFIG_IWLWIFI=y
CONFIG_IWLMVM=y
CONFIG_HID_MULTITOUCH=y
CONFIG_TOUCHSCREEN=y
CONFIG_HID_WACOM=y
CONFIG_IIO=y
CONFIG_HID_SENSOR_HUB=y
CONFIG_HID_SENSOR_ACCEL_3D=y
CONFIG_HID_SENSOR_GYRO_3D=y
CONFIG_MOUSE_PS2_ELANTECH=y
CONFIG_MOUSE_PS2_SYNAPTICS=y
CONFIG_ACPI_BATTERY=y
CONFIG_POWER_SUPPLY=y
CONFIG_MEDIA_SUPPORT=y
CONFIG_MEDIA_CAMERA_SUPPORT=y
CONFIG_VIDEO_DEV=y
CONFIG_VIDEO_V4L2=y
CONFIG_DRM=y
CONFIG_DRM_FBDEV_EMULATION=y
CONFIG_DRM_I915=y
CONFIG_FB=y
CONFIG_FB_VESA=y
CONFIG_FB_EFI=y
CONFIG_FB_SIMPLE=y
CONFIG_FRAMEBUFFER_CONSOLE=y
CONFIG_SOUND=y
CONFIG_SND=y
CONFIG_SND_HDA_INTEL=y
CONFIG_SND_HDA_CODEC_HDMI=y
CONFIG_SND_HDA_CODEC_GENERIC=y
CONFIG_SND_HDA_GENERIC=y
VIVO
make olddefconfig
cp .config "$CONFIGS/rodnik-vivobook-slate13.config"

# === DEPO Storm 3400 ===
echo "=== DEPO Storm 3400 ==="
cp /tmp/rodnik-base.config .config
cat >> .config << 'DEPO'
CONFIG_ICE=y
CONFIG_PCI_IOV=y
CONFIG_BLK_DEV_MD=y
CONFIG_MD_RAID0=y
CONFIG_MD_RAID1=y
CONFIG_MD_RAID10=y
CONFIG_BLK_DEV_NVME=y
CONFIG_SATA_AHCI=y
CONFIG_XFS_FS=y
CONFIG_BTRFS_FS=y
CONFIG_NFS_FS=y
CONFIG_NFSD=y
CONFIG_NUMA=y
CONFIG_TRANSPARENT_HUGEPAGE=y
CONFIG_DRM=n
CONFIG_FB=n
CONFIG_SOUND=n
CONFIG_SND=n
CONFIG_WIRELESS=n
CONFIG_WLAN=n
DEPO
make olddefconfig
cp .config "$CONFIGS/rodnik-depo-storm3400.config"

echo "=== Конфиги созданы ==="
ls -la "$CONFIGS/"
